-- MySQL Script generated by MySQL Workbench
-- Mon 17 Sep 2018 22:21:15 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema noughtsandcrosses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `noughtsandcrosses` ;

-- -----------------------------------------------------
-- Schema noughtsandcrosses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `noughtsandcrosses` DEFAULT CHARACTER SET utf8 ;
USE `noughtsandcrosses` ;

-- -----------------------------------------------------
-- Table `noughtsandcrosses`.`security_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `noughtsandcrosses`.`security_question` ;

CREATE TABLE IF NOT EXISTS `noughtsandcrosses`.`security_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noughtsandcrosses`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `noughtsandcrosses`.`status` ;

CREATE TABLE IF NOT EXISTS `noughtsandcrosses`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noughtsandcrosses`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `noughtsandcrosses`.`user` ;

CREATE TABLE IF NOT EXISTS `noughtsandcrosses`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(35) NOT NULL,
  `password` TEXT NOT NULL,
  `security_question` INT NOT NULL,
  `status` INT NOT NULL,
  `security_answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_security_question_idx` (`security_question` ASC),
  INDEX `fk_user_status1_idx` (`status` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noughtsandcrosses`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `noughtsandcrosses`.`game` ;

CREATE TABLE IF NOT EXISTS `noughtsandcrosses`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `won` INT NOT NULL,
  `lost` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_game_user1_idx` (`won` ASC),
  INDEX `fk_game_user2_idx` (`lost` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
